spring: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 8888
spring: 
  profiles: dev  #开发环境
  application: 
    name: cloud-config-client
---
server: 
  port: 8899
spring: 
  profiles: test  #测试环境
  application: 
    name: cloud-config-client
