
server:
  port: 8004

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///goodsDB?serverTimezone=GMT&characterEncoding=utf-8
    username: root
    password: 123
  application:
    name: provideGoods
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: provideGoods8004
        service-name: ${spring.application.name}
        register: true

mybatis:
  type-aliases-package: com.xz.pojo
  mapper-locations: classpath:/mapper/*.xml

spring: 
  profiles: 
    active: 
    - dev
    

---
server: 
  port: 8888
spring: 
  profiles: dev  #开发环境
  application: 
    name: cloud-config-client
---
server: 
  port: 8899
spring: 
  profiles: test  #测试环境
  application: 
    name: cloud-config-client
